version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./front-end/fantasy-app # path to dockerfile
    ports: # Port binding to host from docker container
      - "4200:4200" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container  
    build: ./back-end/express-api
    ports:
      - "3000:3000"
    container_name: backend-docker
    restart: always
    links:
      - db
  # Create database container
  db:
    build: ./back-end/database
    ports:
      - "5432:5432"
    container_name: database-docker
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    restart: unless-stopped
    volumes:
      - ./data:/data
  scraper:
    build: ./back-end/scripts/KTCScraperScript
    container_name: scraper-cron
